-- MySQL Script generated by MySQL Workbench
-- Sat Apr 23 17:34:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OnlineBookstore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OnlineBookstore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OnlineBookstore` DEFAULT CHARACTER SET utf8 ;
USE `OnlineBookstore` ;

-- -----------------------------------------------------
-- Table `OnlineBookstore`.`Publisher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBookstore`.`Publisher` (
  `Name` VARCHAR(100) NOT NULL,
  `Address` VARCHAR(100) NULL,
  `Phone` VARCHAR(20) NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineBookstore`.`Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBookstore`.`Author` (
  `AuthorID` VARCHAR(20) NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Phone` VARCHAR(20) NULL,
  `Address` VARCHAR(100) NULL,
  PRIMARY KEY (`AuthorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineBookstore`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBookstore`.`Book` (
  `ISBN` VARCHAR(20) NOT NULL,
  `Title` VARCHAR(250) NULL,
  `Date` DATE NULL,
  `Price` FLOAT NULL,
  `PublisherName` VARCHAR(100) NOT NULL,
  `AuthorID` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ISBN`),
  INDEX `fk_Book_Publisher_idx` (`PublisherName` ASC) VISIBLE,
  INDEX `fk_Book_Author1_idx` (`AuthorID` ASC) VISIBLE,
  CONSTRAINT `fk_Book_Publisher`
    FOREIGN KEY (`PublisherName`)
    REFERENCES `OnlineBookstore`.`Publisher` (`Name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Book_Author1`
    FOREIGN KEY (`AuthorID`)
    REFERENCES `OnlineBookstore`.`Author` (`AuthorID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineBookstore`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBookstore`.`Customer` (
  `Email` VARCHAR(150) NOT NULL,
  `Name` VARCHAR(100) NULL,
  `Phone` VARCHAR(20) NULL,
  `Address` VARCHAR(100) NULL,
  PRIMARY KEY (`Email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineBookstore`.`ShoppingCart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBookstore`.`ShoppingCart` (
  `CartID` VARCHAR(20) NOT NULL,
  `CustomerEmail` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`CartID`),
  INDEX `fk_ShoppingCart_Customer1_idx` (`CustomerEmail` ASC) VISIBLE,
  CONSTRAINT `fk_ShoppingCart_Customer1`
    FOREIGN KEY (`CustomerEmail`)
    REFERENCES `OnlineBookstore`.`Customer` (`Email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineBookstore`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBookstore`.`Order` (
  `ISBN` VARCHAR(20) NOT NULL,
  `CartID` VARCHAR(20) NOT NULL,
  `Quantity` INT NULL,
  PRIMARY KEY (`ISBN`, `CartID`),
  INDEX `fk_Book_has_ShoppingCart_ShoppingCart1_idx` (`CartID` ASC) VISIBLE,
  INDEX `fk_Book_has_ShoppingCart_Book1_idx` (`ISBN` ASC) VISIBLE,
  CONSTRAINT `fk_Book_has_ShoppingCart_Book1`
    FOREIGN KEY (`ISBN`)
    REFERENCES `OnlineBookstore`.`Book` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Book_has_ShoppingCart_ShoppingCart1`
    FOREIGN KEY (`CartID`)
    REFERENCES `OnlineBookstore`.`ShoppingCart` (`CartID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineBookstore`.`Warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBookstore`.`Warehouse` (
  `WarehouseID` INT NOT NULL,
  `Phone` VARCHAR(20) NULL,
  `Address` VARCHAR(100) NULL,
  PRIMARY KEY (`WarehouseID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnlineBookstore`.`Stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnlineBookstore`.`Stock` (
  `ISBN` VARCHAR(20) NOT NULL,
  `WarehouseID` INT NOT NULL,
  `Quantity` INT NULL,
  PRIMARY KEY (`ISBN`, `WarehouseID`),
  INDEX `fk_Stock_Warehouse1_idx` (`WarehouseID` ASC) VISIBLE,
  CONSTRAINT `fk_Stock_Book1`
    FOREIGN KEY (`ISBN`)
    REFERENCES `OnlineBookstore`.`Book` (`ISBN`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Stock_Warehouse1`
    FOREIGN KEY (`WarehouseID`)
    REFERENCES `OnlineBookstore`.`Warehouse` (`WarehouseID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
